
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the direct project URL and key
const SUPABASE_URL = "https://bjgzmygqkapsefugfdhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ3pteWdxa2Fwc2VmdWdmZGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjYyNDksImV4cCI6MjA2MTkwMjI0OX0.F1dUSIQPn8Zv2caCYgUcytuRgrEAkuH9yc4PCwcaW7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
